### ISSUE TITLE
Unable to install NextPVR plugin

### ISSUE THREAD

**Issue by samip5** [jellyfin/jellyfin-plugin-nextpvr#18]
Unfortunately, I'm unable to install the version 5 plugin.

Could you please publish the binary in releases of the repository? I was unable to compile it myself either.

```
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: NextPVR
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by crobibero** [comment]
Plugin v5 is for Jellyfin 10.7.
You’re running into https://github.com/jellyfin/jellyfin/issues/4688
